# Estas son las plataformas de modelos de financiamiento compatibles
github: [JJoan02]
patreon: # Reemplazar
open_collective: # Reemplazar con un solo nombre de usuario de Open Collective
ko_fi: # Reemplazar con un solo nombre de usuario de Ko-fi
tidelift: # Reemplazar con un solo nombre de la plataforma y nombre del paquete de Tidelift, por ejemplo, npm/babel
community_bridge: # Reemplazar con un solo nombre de proyecto de Community Bridge, por ejemplo, cloud-foundry
liberapay: # Reemplazar con un solo nombre de usuario de Liberapay
issuehunt: # Reemplazar con un solo nombre de usuario de IssueHunt
otechie: # Reemplazar con un solo nombre de usuario de Otechie
custom: ['https://dash.corinplus.com']
